### ISSUE TITLE
Cannot Set Device UID

### ISSUE THREAD

**Issue by hmorilak** [ngageoint/MAGE#1]
I was creating an admin account and when prompted to set the device UID, the 'finish' button had no affect on the screen. The server did however log this command: 
`2020-02-11T18:37:23.157Z - mongoose: devices.findAndModify({ uid: 'hannah_ubuntu_vm' }, [], { '$set': { description: undefined, userId: undefined, userAgent: undefined, appVersion: undefined, registered: true } })`
Now whenever I try to logon, it allows me to login to my admin account however, the UID never works.  This is what is being logged when this happens:
`2020-02-11T18:42:04.589Z - mongoose: tokens.findOne({ token: 'null' }, { fields: {} }, )`
Any ideas on how to fix this? All help is appreciated :')

**Comment by newmanw** [comment]
Ensure that your value of MAGE_SESSION_COOKIE_SECURE is false, all lowercase. The check in code is strictly not-equal-to the string literal 'false'.

See here: https://github.com/ngageoint/mage-server/issues/57
