### ISSUE TITLE
Pictures across platforms

### ISSUE THREAD

**Issue by roret205** [ngageoint/MAGE#2]
Hey,

I am working with mage and seeing som strange behaviour in the web app and in iOS, Android does not seem to have problems.

When i upload a picture from the web app it is never stored on the server.
When i compare transactions web-app - android i see to put messages from android and one put message from the web-app.

The output from node on the server site, shows that both pictures are received on the the server, but there is some small differences in the fields that are sent from the Web-app and Android.

To me it seems like there is some compatibility issues between the different platforms.

Are other users seeing the same behaviour or does it work for you ?

**Comment by restjohn** [comment]
Also, you mentioned you're having a problem with the iOS app, but only described your issue with the web app.  Are you having the same problem with the iOS app as the web app?  

Does the server save the form data from the web app, and just fail to save the image attachment, or does the server fail to save the entire observation from the web app?

**Comment by roret205** [comment]
Hi,
Thanks for your replies.

The versions is:
Mage server 6.1.0
Web-app The version that is included with 6.10. 
Android App 7.1.2
Browser Safari 13.1.2
               Safari 15.1
               Chrome Version 100.0.4896.127
 IOS - Focus is on Android and web-app for now. But IOS is not showing picots and are not able to download images

The server is hosted at a Centos8 with httpd as reverse proxy.

I have attached a compilation of log files. 
[output.txt](https://github.com/ngageoint/MAGE/files/8596344/output.txt)

**Comment by newmanw** [comment]
@roret205 thanks for log files, unfortunately they stop a little short of what we are looking for.  Uploading an attachment is a two part process, the observation data, which includes attachment metadata is sent first.  You should see another request which will be a file upload request a short time after.  Let's verify both requests.  Here is an example using the network tab from Safari:

First request to save observation data and attachment metadata:
![Screen Shot 2022-04-30 at 7 36 11 AM](https://user-images.githubusercontent.com/3382274/166107804-9e04785d-fc28-4dce-af75-13e7bcb131e2.png)

Second request to upload the attachment file:
![Screen Shot 2022-04-30 at 7 36 24 AM](https://user-images.githubusercontent.com/3382274/166107812-db24de11-01a1-436c-84e4-4024ec1067a1.png)


If the second request is failing, which seems likely given your explanation, can you provide the http error response in the web client as well as corresponding nodejs logs.

**Comment by roret205** [comment]
Hi again,
I really appreciate your help.

It seems like there is a cross origin problem. 
The tages eg. <img src=http:// ....> contains a http reference and not a https. I have solved this by redirecting all requests on port 80 to 443 in a <virtualhost> in apache. What is you opinion?

I have attached the dumps from chrome. I have not found the node.js log (other than the output in the console
![Screen Shot 2022-05-01 at 09 08 35](https://user-images.githubusercontent.com/1254115/166136105-50436803-c8f6-4e06-8d1b-ffa7725336e4.png)
![Screen Shot 2022-05-01 at 09 08 48](https://user-images.githubusercontent.com/1254115/166136110-47cc9143-6023-48a7-b93f-e917316a2769.png)
![Screen Shot 2022-05-01 at 09 08 57](https://user-images.githubusercontent.com/1254115/166136116-058a26d1-0f05-4328-93be-9fafea3394f0.png)


)

**Comment by newmanw** [comment]
@roret205, no problem.  Thanks for digging in a bit more, you re correct your issue lies in retrieving the attachments.  The clients rely on the resource url returned by the server, in your case _http_.  

There is more info in this issue https://github.com/ngageoint/mage-server/pull/56.  the TLDR; for apache is that to include this:

`RequestHeader set X-Forwarded-Proto "https"`

This will make sure that the apache reverse proxy forwards the https scheme to the MAGE server.

**Comment by roret205** [comment]
Thanks a lot for the support to this subject.

I added RequestHeader set X-Forwarded-Proto: _"https" to my virtual host section for the apache remote proxy and now et works on web-app, Android and IOS.
